### ISSUE TITLE
Component 이름 변경 제안

### ISSUE THREAD

**Issue by lazywon** [pp-web-study/attendance-check#3]
아래와 같이 컴포넌트 이름 조금 더 의미에 맞게 변경해 보았습니다. 혹시 의견 있으면 말씀 부탁드립니다 !

룰렛영역 - roulette
친구추천 - invitation -> recommendation
출석현황 - status -> attendanceStatus
달력 - calendar
개근상 - attendanceAward
월별 특별상 - specialAward
당첨자 발표일정 - checkWinner -> winnerInfo
꼭 확인해주세요 - warning -> notice
이벤트 공유 - shareEvent -> share
레이어 팝업 - popUp -> popup

**Comment by OTKRyu** [comment]
변경된 이름으로 반영되었으므로 이 이슈는 닫도록 하겠습니다.
